apiVersion: v2
name: cybershield
description: CyberGuide Career Intelligence Platform - Kubernetes Deployment
type: application
version: 1.11.0
appVersion: "1.11.0"
keywords:
  - cybersecurity
  - career
  - jobs
  - intelligence
maintainers:
  - name: PARTHASARATHI B
    email: parthasarathi442004@gmail.com
home: https://github.com/partha442004/CyberGuide
sources:
  - https://github.com/partha442004/CyberGuide
